# Copyright 2026 Jay Cheng
# Licensed under the Apache License, Version 2.0 (see LICENSE).
"""`lyrithm init <name>` — scaffold a new strategy project."""
from __future__ import annotations

import json
from pathlib import Path

import click

from ..manifest import NAME_RE

_LYRITHM_YAML = """\
name: {name}
display_name: "{display}"
language: python
entrypoint: strategy.py
version: 0.1.0
description: "Describe your strategy in a single sentence."
author: ""
tags: []
source_visibility: closed   # 'closed' = users can use/tune but never see source; 'open' = forkable
config_schema: config_schema.json
default_config:
  ema_fast: 12
  ema_slow: 26
  stop_atr_mult: 1.5
"""

_STRATEGY_PY = '''\
"""Skeleton strategy generated by `lyrithm init`. Edit freely."""
from __future__ import annotations

from typing import Any, Mapping

from lyrithm_sdk import Candle, Strategy
from lyrithm_sdk.indicators import ATR, EMA


class MyStrategy(Strategy):
    def __init__(self, config: Mapping[str, Any]):
        self.ema_fast = EMA(int(config.get("ema_fast", 12)))
        self.ema_slow = EMA(int(config.get("ema_slow", 26)))
        self.atr = ATR(14)
        self.stop_atr_mult = float(config.get("stop_atr_mult", 1.5))
        self._prev_diff: float | None = None
        self._last: Candle | None = None

    def update(self, candle: Candle) -> None:
        self.ema_fast.update(candle.close)
        self.ema_slow.update(candle.close)
        self.atr.update(candle)
        self._last = candle

    def is_ready(self) -> bool:
        return self.ema_fast.is_ready() and self.ema_slow.is_ready() and self.atr.is_ready()

    def check_long_entry(self) -> int:
        diff = self.ema_fast.get_value() - self.ema_slow.get_value()
        fired = self._prev_diff is not None and self._prev_diff <= 0 < diff
        self._prev_diff = diff
        return 1 if fired else 0

    def check_short_entry(self) -> int:
        diff = self.ema_fast.get_value() - self.ema_slow.get_value()
        fired = self._prev_diff is not None and self._prev_diff >= 0 > diff
        return 1 if fired else 0

    def calculate_long_stop_loss(self) -> float:
        assert self._last is not None
        return self._last.close - self.atr.get_value() * self.stop_atr_mult

    def calculate_short_stop_loss(self) -> float:
        assert self._last is not None
        return self._last.close + self.atr.get_value() * self.stop_atr_mult

    def get_dynamic_reward_ratio(self) -> float:
        return 2.0

    def get_dynamic_leverage(self) -> int:
        return 5

    def reset(self) -> None:
        self.ema_fast.reset()
        self.ema_slow.reset()
        self.atr.reset()
        self._prev_diff = None
        self._last = None


def create_strategy(config: Mapping[str, Any]) -> Strategy:
    """Factory entry point — the loader calls this with the resolved config dict."""
    return MyStrategy(config or {})
'''

_CONFIG_SCHEMA = {
    "title": "My Strategy",
    "groups": [
        {
            "name": "EMA",
            "fields": {
                "ema_fast": {
                    "type": "integer",
                    "min": 2,
                    "max": 500,
                    "default": 12,
                    "label": "EMA Fast",
                    "tunable": True,
                },
                "ema_slow": {
                    "type": "integer",
                    "min": 5,
                    "max": 1000,
                    "default": 26,
                    "label": "EMA Slow",
                    "tunable": True,
                },
            },
        },
        {
            "name": "Risk",
            "fields": {
                "stop_atr_mult": {
                    "type": "number",
                    "min": 0.1,
                    "max": 10.0,
                    "default": 1.5,
                    "label": "Stop = ATR ×",
                    "tunable": True,
                }
            },
        },
    ],
}

_README = """\
# {display}

A Lyrithm strategy scaffolded by `lyrithm init`.

## Local test

```bash
lyrithm test --csv data/sample.csv
```

## Publish

```bash
lyrithm package
lyrithm publish --api https://api.lyrithm.com
```
"""


@click.command()
@click.argument("name")
@click.option(
    "--dir",
    "target_dir",
    default=None,
    help="Parent directory. Defaults to the current working directory.",
)
def init(name: str, target_dir: str | None) -> None:
    """Scaffold a new strategy package in ./<name>/."""
    if not NAME_RE.match(name):
        raise click.ClickException(
            f"invalid name '{name}'; lowercase letters/digits/hyphens, 2-63 chars, must start with a letter"
        )

    parent = Path(target_dir) if target_dir else Path.cwd()
    project = parent / name
    if project.exists():
        raise click.ClickException(f"{project} already exists; refusing to overwrite")

    project.mkdir(parents=True)
    display = " ".join(w.capitalize() for w in name.replace("-", " ").split())

    (project / "lyrithm.yaml").write_text(_LYRITHM_YAML.format(name=name, display=display), encoding="utf-8")
    (project / "strategy.py").write_text(_STRATEGY_PY, encoding="utf-8")
    (project / "config_schema.json").write_text(
        json.dumps(_CONFIG_SCHEMA, indent=2) + "\n", encoding="utf-8"
    )
    (project / "README.md").write_text(_README.format(display=display), encoding="utf-8")

    click.echo(f"Created {project}")
    click.echo("Next:")
    click.echo(f"  cd {name}")
    click.echo("  lyrithm test --csv path/to/candles.csv")
